// Code generated by ent, DO NOT EDIT.

package userloginmethod

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userloginmethod type in the database.
	Label = "user_login_method"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLoginType holds the string denoting the login_type field in the database.
	FieldLoginType = "login_type"
	// FieldIdentifier holds the string denoting the identifier field in the database.
	FieldIdentifier = "identifier"
	// Table holds the table name of the userloginmethod in the database.
	Table = "user_login_methods"
)

// Columns holds all SQL columns for userloginmethod fields.
var Columns = []string{
	FieldID,
	FieldLoginType,
	FieldIdentifier,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_login_methods"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_login_methods",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UserLoginMethod queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLoginType orders the results by the login_type field.
func ByLoginType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginType, opts...).ToFunc()
}

// ByIdentifier orders the results by the identifier field.
func ByIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentifier, opts...).ToFunc()
}
