// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PlatformAccountsColumns holds the columns for the "platform_accounts" table.
	PlatformAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
	}
	// PlatformAccountsTable holds the schema information for the "platform_accounts" table.
	PlatformAccountsTable = &schema.Table{
		Name:       "platform_accounts",
		Columns:    PlatformAccountsColumns,
		PrimaryKey: []*schema.Column{PlatformAccountsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PlatformAccountsTable,
	}
)

func init() {
}
