// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysatom/framework/ent/predicate"
	"github.com/sysatom/framework/ent/userloginmethod"
)

// UserLoginMethodQuery is the builder for querying UserLoginMethod entities.
type UserLoginMethodQuery struct {
	config
	ctx        *QueryContext
	order      []userloginmethod.OrderOption
	inters     []Interceptor
	predicates []predicate.UserLoginMethod
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserLoginMethodQuery builder.
func (ulmq *UserLoginMethodQuery) Where(ps ...predicate.UserLoginMethod) *UserLoginMethodQuery {
	ulmq.predicates = append(ulmq.predicates, ps...)
	return ulmq
}

// Limit the number of records to be returned by this query.
func (ulmq *UserLoginMethodQuery) Limit(limit int) *UserLoginMethodQuery {
	ulmq.ctx.Limit = &limit
	return ulmq
}

// Offset to start from.
func (ulmq *UserLoginMethodQuery) Offset(offset int) *UserLoginMethodQuery {
	ulmq.ctx.Offset = &offset
	return ulmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulmq *UserLoginMethodQuery) Unique(unique bool) *UserLoginMethodQuery {
	ulmq.ctx.Unique = &unique
	return ulmq
}

// Order specifies how the records should be ordered.
func (ulmq *UserLoginMethodQuery) Order(o ...userloginmethod.OrderOption) *UserLoginMethodQuery {
	ulmq.order = append(ulmq.order, o...)
	return ulmq
}

// First returns the first UserLoginMethod entity from the query.
// Returns a *NotFoundError when no UserLoginMethod was found.
func (ulmq *UserLoginMethodQuery) First(ctx context.Context) (*UserLoginMethod, error) {
	nodes, err := ulmq.Limit(1).All(setContextOp(ctx, ulmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userloginmethod.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) FirstX(ctx context.Context) *UserLoginMethod {
	node, err := ulmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserLoginMethod ID from the query.
// Returns a *NotFoundError when no UserLoginMethod ID was found.
func (ulmq *UserLoginMethodQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulmq.Limit(1).IDs(setContextOp(ctx, ulmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userloginmethod.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) FirstIDX(ctx context.Context) int {
	id, err := ulmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserLoginMethod entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserLoginMethod entity is found.
// Returns a *NotFoundError when no UserLoginMethod entities are found.
func (ulmq *UserLoginMethodQuery) Only(ctx context.Context) (*UserLoginMethod, error) {
	nodes, err := ulmq.Limit(2).All(setContextOp(ctx, ulmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userloginmethod.Label}
	default:
		return nil, &NotSingularError{userloginmethod.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) OnlyX(ctx context.Context) *UserLoginMethod {
	node, err := ulmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserLoginMethod ID in the query.
// Returns a *NotSingularError when more than one UserLoginMethod ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulmq *UserLoginMethodQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulmq.Limit(2).IDs(setContextOp(ctx, ulmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userloginmethod.Label}
	default:
		err = &NotSingularError{userloginmethod.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserLoginMethods.
func (ulmq *UserLoginMethodQuery) All(ctx context.Context) ([]*UserLoginMethod, error) {
	ctx = setContextOp(ctx, ulmq.ctx, ent.OpQueryAll)
	if err := ulmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserLoginMethod, *UserLoginMethodQuery]()
	return withInterceptors[[]*UserLoginMethod](ctx, ulmq, qr, ulmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) AllX(ctx context.Context) []*UserLoginMethod {
	nodes, err := ulmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserLoginMethod IDs.
func (ulmq *UserLoginMethodQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulmq.ctx.Unique == nil && ulmq.path != nil {
		ulmq.Unique(true)
	}
	ctx = setContextOp(ctx, ulmq.ctx, ent.OpQueryIDs)
	if err = ulmq.Select(userloginmethod.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) IDsX(ctx context.Context) []int {
	ids, err := ulmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulmq *UserLoginMethodQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulmq.ctx, ent.OpQueryCount)
	if err := ulmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulmq, querierCount[*UserLoginMethodQuery](), ulmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) CountX(ctx context.Context) int {
	count, err := ulmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulmq *UserLoginMethodQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulmq.ctx, ent.OpQueryExist)
	switch _, err := ulmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulmq *UserLoginMethodQuery) ExistX(ctx context.Context) bool {
	exist, err := ulmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserLoginMethodQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulmq *UserLoginMethodQuery) Clone() *UserLoginMethodQuery {
	if ulmq == nil {
		return nil
	}
	return &UserLoginMethodQuery{
		config:     ulmq.config,
		ctx:        ulmq.ctx.Clone(),
		order:      append([]userloginmethod.OrderOption{}, ulmq.order...),
		inters:     append([]Interceptor{}, ulmq.inters...),
		predicates: append([]predicate.UserLoginMethod{}, ulmq.predicates...),
		// clone intermediate query.
		sql:  ulmq.sql.Clone(),
		path: ulmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LoginType string `json:"login_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserLoginMethod.Query().
//		GroupBy(userloginmethod.FieldLoginType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulmq *UserLoginMethodQuery) GroupBy(field string, fields ...string) *UserLoginMethodGroupBy {
	ulmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserLoginMethodGroupBy{build: ulmq}
	grbuild.flds = &ulmq.ctx.Fields
	grbuild.label = userloginmethod.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LoginType string `json:"login_type,omitempty"`
//	}
//
//	client.UserLoginMethod.Query().
//		Select(userloginmethod.FieldLoginType).
//		Scan(ctx, &v)
func (ulmq *UserLoginMethodQuery) Select(fields ...string) *UserLoginMethodSelect {
	ulmq.ctx.Fields = append(ulmq.ctx.Fields, fields...)
	sbuild := &UserLoginMethodSelect{UserLoginMethodQuery: ulmq}
	sbuild.label = userloginmethod.Label
	sbuild.flds, sbuild.scan = &ulmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserLoginMethodSelect configured with the given aggregations.
func (ulmq *UserLoginMethodQuery) Aggregate(fns ...AggregateFunc) *UserLoginMethodSelect {
	return ulmq.Select().Aggregate(fns...)
}

func (ulmq *UserLoginMethodQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulmq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulmq.ctx.Fields {
		if !userloginmethod.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulmq.path != nil {
		prev, err := ulmq.path(ctx)
		if err != nil {
			return err
		}
		ulmq.sql = prev
	}
	return nil
}

func (ulmq *UserLoginMethodQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserLoginMethod, error) {
	var (
		nodes   = []*UserLoginMethod{}
		withFKs = ulmq.withFKs
		_spec   = ulmq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userloginmethod.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserLoginMethod).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserLoginMethod{config: ulmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ulmq *UserLoginMethodQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulmq.querySpec()
	_spec.Node.Columns = ulmq.ctx.Fields
	if len(ulmq.ctx.Fields) > 0 {
		_spec.Unique = ulmq.ctx.Unique != nil && *ulmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulmq.driver, _spec)
}

func (ulmq *UserLoginMethodQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userloginmethod.Table, userloginmethod.Columns, sqlgraph.NewFieldSpec(userloginmethod.FieldID, field.TypeInt))
	_spec.From = ulmq.sql
	if unique := ulmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulmq.path != nil {
		_spec.Unique = true
	}
	if fields := ulmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userloginmethod.FieldID)
		for i := range fields {
			if fields[i] != userloginmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulmq *UserLoginMethodQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulmq.driver.Dialect())
	t1 := builder.Table(userloginmethod.Table)
	columns := ulmq.ctx.Fields
	if len(columns) == 0 {
		columns = userloginmethod.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulmq.sql != nil {
		selector = ulmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulmq.ctx.Unique != nil && *ulmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulmq.predicates {
		p(selector)
	}
	for _, p := range ulmq.order {
		p(selector)
	}
	if offset := ulmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserLoginMethodGroupBy is the group-by builder for UserLoginMethod entities.
type UserLoginMethodGroupBy struct {
	selector
	build *UserLoginMethodQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulmgb *UserLoginMethodGroupBy) Aggregate(fns ...AggregateFunc) *UserLoginMethodGroupBy {
	ulmgb.fns = append(ulmgb.fns, fns...)
	return ulmgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulmgb *UserLoginMethodGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulmgb.build.ctx, ent.OpQueryGroupBy)
	if err := ulmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserLoginMethodQuery, *UserLoginMethodGroupBy](ctx, ulmgb.build, ulmgb, ulmgb.build.inters, v)
}

func (ulmgb *UserLoginMethodGroupBy) sqlScan(ctx context.Context, root *UserLoginMethodQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulmgb.fns))
	for _, fn := range ulmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulmgb.flds)+len(ulmgb.fns))
		for _, f := range *ulmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserLoginMethodSelect is the builder for selecting fields of UserLoginMethod entities.
type UserLoginMethodSelect struct {
	*UserLoginMethodQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ulms *UserLoginMethodSelect) Aggregate(fns ...AggregateFunc) *UserLoginMethodSelect {
	ulms.fns = append(ulms.fns, fns...)
	return ulms
}

// Scan applies the selector query and scans the result into the given value.
func (ulms *UserLoginMethodSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulms.ctx, ent.OpQuerySelect)
	if err := ulms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserLoginMethodQuery, *UserLoginMethodSelect](ctx, ulms.UserLoginMethodQuery, ulms, ulms.inters, v)
}

func (ulms *UserLoginMethodSelect) sqlScan(ctx context.Context, root *UserLoginMethodQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ulms.fns))
	for _, fn := range ulms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ulms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
