// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Private"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello/{id}": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Show an account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.FileDef"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.FileDef": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "id        Uid",
                    "type": "string"
                },
                "id": {
                    "description": "using string to get around rethinkdb's problems with uint64;\n` + "`" + `bson:\"_id\"` + "`" + ` tag is for mongodb to use as primary key '_id'.",
                    "type": "string"
                },
                "location": {
                    "description": "Internal file location, i.e. path on disk or an S3 blob address.",
                    "type": "string"
                },
                "mimeType": {
                    "description": "Type of the file.",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the file",
                    "type": "string"
                },
                "size": {
                    "description": "Size of the file in bytes.",
                    "type": "integer"
                },
                "status": {
                    "description": "Status of upload",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "description": "User who created the file",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "access token",
            "type": "apiKey",
            "name": "X-AccessToken",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6060",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Bussiness API",
	Description:      "Bussiness API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
