basePath: /service
host: localhost:6060
info:
  contact: {}
  description: Flowbot Chatbot API
  license:
    name: GPL 3.0
    url: https://github.com/sysatom/framework/blob/master/LICENSE
  title: Flowbot API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    description: access token
    in: header
    name: X-AccessToken
    type: apiKey
swagger: "2.0"
