basePath: /
definitions:
  types.FileDef:
    properties:
      createdAt:
        description: id        Uid
        type: string
      id:
        description: |-
          using string to get around rethinkdb's problems with uint64;
          `bson:"_id"` tag is for mongodb to use as primary key '_id'.
        type: string
      location:
        description: Internal file location, i.e. path on disk or an S3 blob address.
        type: string
      mimeType:
        description: Type of the file.
        type: string
      name:
        description: Name of the file
        type: string
      size:
        description: Size of the file in bytes.
        type: integer
      status:
        description: Status of upload
        type: integer
      updatedAt:
        type: string
      user:
        description: User who created the file
        type: string
    type: object
host: localhost:6060
info:
  contact: {}
  description: Bussiness API
  license:
    name: Private
  title: Bussiness API
  version: "1.0"
paths:
  /hello/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.FileDef'
      summary: Show an account
      tags:
      - accounts
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    description: access token
    in: header
    name: X-AccessToken
    type: apiKey
swagger: "2.0"
