// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PlatformAccount is the predicate function for platformaccount builders.
type PlatformAccount func(*sql.Selector)
